# Generated by Django 3.2.6 on 2022-09-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_class_year'),
        ('users', '0003_auto_20210814_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='challenges_done',
            field=models.ManyToManyField(blank=True, related_name='users_that_completed', to='main.Challenge'),
        ),
    ]
