# Generated by Django 4.2.5 on 2023-09-19 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_dark_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_submission_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 19, 22, 47, 8, 762498, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
