# Generated by Django 4.2.5 on 2023-09-19 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_last_submission_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_submission_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
