# Generated by Django 3.2.6 on 2022-09-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_challenge_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.CharField(choices=[('2023', 'Seniors'), ('2024', 'Juniors'), ('2025', 'Sophomores'), ('2026', 'Freshmen')], max_length=20, unique=True),
        ),
    ]
