# Generated by Django 4.2.5 on 2023-09-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_class_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="flag",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="class",
            name="year",
            field=models.CharField(
                choices=[
                    ("2024", "Seniors"),
                    ("2025", "Juniors"),
                    ("2026", "Sophomores"),
                    ("2027", "Freshmen"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
