# Generated by Django 4.2.5 on 2023-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_challenge_flag_alter_class_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="flag",
            field=models.CharField(max_length=1024),
        ),
    ]
