# Generated by Django 4.2.5 on 2024-09-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_challenge_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.CharField(choices=[('2025', 'Seniors'), ('2026', 'Juniors'), ('2027', 'Sophomores'), ('2028', 'Freshmen')], max_length=20, unique=True),
        ),
    ]
