# Generated by Django 4.2.5 on 2025-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.CharField(choices=[('2026', 'Seniors'), ('2027', 'Juniors'), ('2028', 'Sophomores'), ('2029', 'Freshmen')], max_length=20, unique=True),
        ),
    ]
