# Generated by Django 4.2.5 on 2025-08-24 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0017_siteconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='logging_pag_timesta_ff5503_idx'), models.Index(fields=['user', 'timestamp'], name='logging_pag_user_id_2fb977_idx'), models.Index(fields=['path', 'timestamp'], name='logging_pag_path_e33f97_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlagSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_flag', models.CharField(max_length=1024)),
                ('is_correct', models.BooleanField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['challenge', 'timestamp'], name='logging_fla_challen_1e30bf_idx'), models.Index(fields=['user', 'timestamp'], name='logging_fla_user_id_2f8b8c_idx'), models.Index(fields=['is_correct', 'timestamp'], name='logging_fla_is_corr_2f7919_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeCompletion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_year', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('points_earned', models.IntegerField()),
                ('first_completion_for_class', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='main.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['challenge', 'timestamp'], name='logging_cha_challen_53b277_idx'), models.Index(fields=['class_year', 'timestamp'], name='logging_cha_class_y_7bdddf_idx'), models.Index(fields=['timestamp'], name='logging_cha_timesta_4ee2be_idx')],
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('flag_correct', 'Correct Flag Submission'), ('flag_incorrect', 'Incorrect Flag Submission'), ('challenge_completed', 'Challenge Completed'), ('page_view', 'Page View'), ('admin_action', 'Admin Action')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='logging_act_timesta_0e32ee_idx'), models.Index(fields=['user', 'timestamp'], name='logging_act_user_id_42e26f_idx'), models.Index(fields=['activity_type', 'timestamp'], name='logging_act_activit_013130_idx')],
            },
        ),
    ]
